apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: h653f5kn8-nodejs
  janus-idp.io/tekton: h653f5kn8-nodejs
  backstage.io/kubernetes-id: h653f5kn8-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: h653f5kn8-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
